# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: bx2cloud
release:
  github:
    owner: BenasB
    name: bx2cloud

builds:
  - id: api
    main: ./cmd/bx2cloud-api
    binary: bx2cloud-api
    goos: [linux]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=1

  - id: cli
    main: ./cmd/bx2cloud
    binary: bx2cloud
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

  - id: terraform-provider
    main: ./cmd/terraform-provider-bx2cloud
    binary: terraform-provider-bx2cloud
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - formats: [tar.gz]
    ids: [api, cli, terraform-provider]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  use: git

