# https://taskfile.dev

version: "3"

tasks:
  pb-generate:
    desc: Generate Go protobuf and gRPC code
    dir: internal/api/pb
    cmds:
      - protoc
        --go_out=. --go_opt=paths=source_relative
        --go-grpc_out=. --go-grpc_opt=paths=source_relative
        *.proto

  tf-test:
    desc: Run acceptance tests for the terraform provider
    dir: internal/terraform
    env:
      TF_ACC: 1
    cmds:
      - go test -count=1 -v
  
  tf-build:
    desc: Build terraform provider in examples directory
    cmds:
      - go build -o ./examples/terraform/providers/local/benasb/bx2cloud/1.0.0/windows_amd64/terraform-provider-bx2cloud.exe ./cmd/terraform/

  tf-reinit-examples:
    desc: Clean up terraform examples and rerun `terraform init`
    deps: [tf-build]
    vars:
      TF_EXAMPLE_DIRS:
        sh: find examples/terraform -name 'main.tf' -printf '%h\n'
    cmds:
      - for: { var: TF_EXAMPLE_DIRS }
        cmd: |
          rm -rf "{{.ITEM}}/.terraform" "{{.ITEM}}/.terraform.lock.hcl"; \
          terraform -chdir={{.ITEM}} init -plugin-dir=../providers > /dev/null; \

  tf-docs-generate:
    desc: Generate Terraform provider documentation in docs/
    cmds:
      - go run -modfile ./tools/go.mod github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs generate --provider-dir ./cmd/terraform --provider-name bx2cloud --examples-dir ../../internal/terraform/examples --rendered-website-dir ../../docs/docs/terraform/autogenerated
      - task: tf-docs-docusaurify

  tf-docs-docusaurify:
    desc: Adjust documentation generated by tfplugindocs to docusaurus supported attributed
    vars:
      DATA_SOURCES:
        sh: find docs/docs/terraform/autogenerated/data-sources -name '*.md'
      RESOURCES:
        sh: find docs/docs/terraform/autogenerated/resources -name '*.md'
    cmds:
      - "echo '{\"position\": 2, \"label\": \"Reference\", \"link\": { \"type\": \"generated-index\", \"title\": \"Terraform provider reference\" }}' > ./docs/docs/terraform/autogenerated/_category_.json"
      - "mv ./docs/docs/terraform/autogenerated/index.md ./docs/docs/terraform/autogenerated/provider.md"
      - "sed -i '/^page_title:/c\\title: Provider\\nsidebar_position: 1\\ncustom_edit_url: null' ./docs/docs/terraform/autogenerated/provider.md"
      - "echo '{\"position\": 2, \"label\": \"Data sources\"}' > ./docs/docs/terraform/autogenerated/data-sources/_category_.json"
      - "echo '{\"position\": 3, \"label\": \"Resources\"}' > ./docs/docs/terraform/autogenerated/resources/_category_.json"
      - for: { var: DATA_SOURCES }
        cmd: "sed -i -E 's/^page_title: \"([^ ]+).*$/title: \"\\1\"\\ncustom_edit_url: null/' {{.ITEM}}"
      - for: { var: RESOURCES }
        cmd: "sed -i -E 's/^page_title: \"([^ ]+).*$/title: \"\\1\"\\ncustom_edit_url: null/' {{.ITEM}}"
