// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: container.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerIdentificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerIdentificationRequest) Reset() {
	*x = ContainerIdentificationRequest{}
	mi := &file_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerIdentificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerIdentificationRequest) ProtoMessage() {}

func (x *ContainerIdentificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerIdentificationRequest.ProtoReflect.Descriptor instead.
func (*ContainerIdentificationRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerIdentificationRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ContainerCreationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubnetworkId  uint32                 `protobuf:"varint,1,opt,name=subnetwork_id,json=subnetworkId,proto3" json:"subnetwork_id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerCreationRequest) Reset() {
	*x = ContainerCreationRequest{}
	mi := &file_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerCreationRequest) ProtoMessage() {}

func (x *ContainerCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerCreationRequest.ProtoReflect.Descriptor instead.
func (*ContainerCreationRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerCreationRequest) GetSubnetworkId() uint32 {
	if x != nil {
		return x.SubnetworkId
	}
	return 0
}

func (x *ContainerCreationRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       uint32                 `protobuf:"fixed32,2,opt,name=address,proto3" json:"address,omitempty"`
	PrefixLength  uint32                 `protobuf:"fixed32,3,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	Status        uint32                 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{2}
}

func (x *Container) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Container) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *Container) GetPrefixLength() uint32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

func (x *Container) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_container_proto protoreflect.FileDescriptor

const file_container_proto_rawDesc = "" +
	"\n" +
	"\x0fcontainer.proto\x12\bbx2cloud\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\x1eContainerIdentificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"U\n" +
	"\x18ContainerCreationRequest\x12#\n" +
	"\rsubnetwork_id\x18\x01 \x01(\rR\fsubnetworkId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"\xc2\x01\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\aR\aaddress\x12#\n" +
	"\rprefix_length\x18\x03 \x01(\aR\fprefixLength\x12\x16\n" +
	"\x06status\x18\x04 \x01(\rR\x06status\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x128\n" +
	"\tcreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\x9e\x02\n" +
	"\x10ContainerService\x12D\n" +
	"\x03Get\x12(.bx2cloud.ContainerIdentificationRequest\x1a\x13.bx2cloud.Container\x125\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x13.bx2cloud.Container0\x01\x12A\n" +
	"\x06Create\x12\".bx2cloud.ContainerCreationRequest\x1a\x13.bx2cloud.Container\x12J\n" +
	"\x06Delete\x12(.bx2cloud.ContainerIdentificationRequest\x1a\x16.google.protobuf.EmptyB,Z*github.com/BenasB/bx2cloud/internal/api/pbb\x06proto3"

var (
	file_container_proto_rawDescOnce sync.Once
	file_container_proto_rawDescData []byte
)

func file_container_proto_rawDescGZIP() []byte {
	file_container_proto_rawDescOnce.Do(func() {
		file_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_container_proto_rawDesc), len(file_container_proto_rawDesc)))
	})
	return file_container_proto_rawDescData
}

var file_container_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_container_proto_goTypes = []any{
	(*ContainerIdentificationRequest)(nil), // 0: bx2cloud.ContainerIdentificationRequest
	(*ContainerCreationRequest)(nil),       // 1: bx2cloud.ContainerCreationRequest
	(*Container)(nil),                      // 2: bx2cloud.Container
	(*timestamppb.Timestamp)(nil),          // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 4: google.protobuf.Empty
}
var file_container_proto_depIdxs = []int32{
	3, // 0: bx2cloud.Container.createdAt:type_name -> google.protobuf.Timestamp
	0, // 1: bx2cloud.ContainerService.Get:input_type -> bx2cloud.ContainerIdentificationRequest
	4, // 2: bx2cloud.ContainerService.List:input_type -> google.protobuf.Empty
	1, // 3: bx2cloud.ContainerService.Create:input_type -> bx2cloud.ContainerCreationRequest
	0, // 4: bx2cloud.ContainerService.Delete:input_type -> bx2cloud.ContainerIdentificationRequest
	2, // 5: bx2cloud.ContainerService.Get:output_type -> bx2cloud.Container
	2, // 6: bx2cloud.ContainerService.List:output_type -> bx2cloud.Container
	2, // 7: bx2cloud.ContainerService.Create:output_type -> bx2cloud.Container
	4, // 8: bx2cloud.ContainerService.Delete:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_container_proto_init() }
func file_container_proto_init() {
	if File_container_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_container_proto_rawDesc), len(file_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_container_proto_goTypes,
		DependencyIndexes: file_container_proto_depIdxs,
		MessageInfos:      file_container_proto_msgTypes,
	}.Build()
	File_container_proto = out.File
	file_container_proto_goTypes = nil
	file_container_proto_depIdxs = nil
}
