// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: container.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerIdentificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerIdentificationRequest) Reset() {
	*x = ContainerIdentificationRequest{}
	mi := &file_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerIdentificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerIdentificationRequest) ProtoMessage() {}

func (x *ContainerIdentificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerIdentificationRequest.ProtoReflect.Descriptor instead.
func (*ContainerIdentificationRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerIdentificationRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ContainerCreationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubnetworkId  uint32                 `protobuf:"varint,1,opt,name=subnetwork_id,json=subnetworkId,proto3" json:"subnetwork_id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Entrypoint    []string               `protobuf:"bytes,3,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Cmd           []string               `protobuf:"bytes,4,rep,name=cmd,proto3" json:"cmd,omitempty"`
	Env           []string               `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerCreationRequest) Reset() {
	*x = ContainerCreationRequest{}
	mi := &file_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerCreationRequest) ProtoMessage() {}

func (x *ContainerCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerCreationRequest.ProtoReflect.Descriptor instead.
func (*ContainerCreationRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerCreationRequest) GetSubnetworkId() uint32 {
	if x != nil {
		return x.SubnetworkId
	}
	return 0
}

func (x *ContainerCreationRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerCreationRequest) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *ContainerCreationRequest) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *ContainerCreationRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       uint32                 `protobuf:"fixed32,2,opt,name=address,proto3" json:"address,omitempty"`
	PrefixLength  uint32                 `protobuf:"fixed32,3,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	SubnetworkId  uint32                 `protobuf:"varint,8,opt,name=subnetwork_id,json=subnetworkId,proto3" json:"subnetwork_id,omitempty"`
	Entrypoint    []string               `protobuf:"bytes,9,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Cmd           []string               `protobuf:"bytes,10,rep,name=cmd,proto3" json:"cmd,omitempty"`
	Env           []string               `protobuf:"bytes,11,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{2}
}

func (x *Container) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Container) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *Container) GetPrefixLength() uint32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Container) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Container) GetSubnetworkId() uint32 {
	if x != nil {
		return x.SubnetworkId
	}
	return 0
}

func (x *Container) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *Container) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *Container) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ContainerExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*ContainerExecRequest_Initialization
	//	*ContainerExecRequest_Stdin
	Input         isContainerExecRequest_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerExecRequest) Reset() {
	*x = ContainerExecRequest{}
	mi := &file_container_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerExecRequest) ProtoMessage() {}

func (x *ContainerExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerExecRequest.ProtoReflect.Descriptor instead.
func (*ContainerExecRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerExecRequest) GetInput() isContainerExecRequest_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ContainerExecRequest) GetInitialization() *ContainerExecInitializationRequest {
	if x != nil {
		if x, ok := x.Input.(*ContainerExecRequest_Initialization); ok {
			return x.Initialization
		}
	}
	return nil
}

func (x *ContainerExecRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Input.(*ContainerExecRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

type isContainerExecRequest_Input interface {
	isContainerExecRequest_Input()
}

type ContainerExecRequest_Initialization struct {
	Initialization *ContainerExecInitializationRequest `protobuf:"bytes,1,opt,name=initialization,proto3,oneof"`
}

type ContainerExecRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

func (*ContainerExecRequest_Initialization) isContainerExecRequest_Input() {}

func (*ContainerExecRequest_Stdin) isContainerExecRequest_Input() {}

type ContainerExecInitializationRequest struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	Identification *ContainerIdentificationRequest `protobuf:"bytes,1,opt,name=identification,proto3" json:"identification,omitempty"`
	ConsoleWidth   int32                           `protobuf:"varint,2,opt,name=console_width,json=consoleWidth,proto3" json:"console_width,omitempty"`
	ConsoleHeight  int32                           `protobuf:"varint,3,opt,name=console_height,json=consoleHeight,proto3" json:"console_height,omitempty"`
	Terminal       *string                         `protobuf:"bytes,4,opt,name=terminal,proto3,oneof" json:"terminal,omitempty"`
	Args           []string                        `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContainerExecInitializationRequest) Reset() {
	*x = ContainerExecInitializationRequest{}
	mi := &file_container_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerExecInitializationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerExecInitializationRequest) ProtoMessage() {}

func (x *ContainerExecInitializationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerExecInitializationRequest.ProtoReflect.Descriptor instead.
func (*ContainerExecInitializationRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerExecInitializationRequest) GetIdentification() *ContainerIdentificationRequest {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *ContainerExecInitializationRequest) GetConsoleWidth() int32 {
	if x != nil {
		return x.ConsoleWidth
	}
	return 0
}

func (x *ContainerExecInitializationRequest) GetConsoleHeight() int32 {
	if x != nil {
		return x.ConsoleHeight
	}
	return 0
}

func (x *ContainerExecInitializationRequest) GetTerminal() string {
	if x != nil && x.Terminal != nil {
		return *x.Terminal
	}
	return ""
}

func (x *ContainerExecInitializationRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ContainerExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*ContainerExecResponse_Stdout
	//	*ContainerExecResponse_ExitCode
	Output        isContainerExecResponse_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerExecResponse) Reset() {
	*x = ContainerExecResponse{}
	mi := &file_container_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerExecResponse) ProtoMessage() {}

func (x *ContainerExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerExecResponse.ProtoReflect.Descriptor instead.
func (*ContainerExecResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerExecResponse) GetOutput() isContainerExecResponse_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ContainerExecResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Output.(*ContainerExecResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ContainerExecResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Output.(*ContainerExecResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isContainerExecResponse_Output interface {
	isContainerExecResponse_Output()
}

type ContainerExecResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ContainerExecResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*ContainerExecResponse_Stdout) isContainerExecResponse_Output() {}

func (*ContainerExecResponse_ExitCode) isContainerExecResponse_Output() {}

type ContainerLogsRequest struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	Identification *ContainerIdentificationRequest `protobuf:"bytes,1,opt,name=identification,proto3" json:"identification,omitempty"`
	Follow         bool                            `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContainerLogsRequest) Reset() {
	*x = ContainerLogsRequest{}
	mi := &file_container_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLogsRequest) ProtoMessage() {}

func (x *ContainerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLogsRequest.ProtoReflect.Descriptor instead.
func (*ContainerLogsRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerLogsRequest) GetIdentification() *ContainerIdentificationRequest {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *ContainerLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type ContainerLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerLogsResponse) Reset() {
	*x = ContainerLogsResponse{}
	mi := &file_container_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLogsResponse) ProtoMessage() {}

func (x *ContainerLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLogsResponse.ProtoReflect.Descriptor instead.
func (*ContainerLogsResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerLogsResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_container_proto protoreflect.FileDescriptor

const file_container_proto_rawDesc = "" +
	"\n" +
	"\x0fcontainer.proto\x12\bbx2cloud\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\x1eContainerIdentificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x99\x01\n" +
	"\x18ContainerCreationRequest\x12#\n" +
	"\rsubnetwork_id\x18\x01 \x01(\rR\fsubnetworkId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x03 \x03(\tR\n" +
	"entrypoint\x12\x10\n" +
	"\x03cmd\x18\x04 \x03(\tR\x03cmd\x12\x10\n" +
	"\x03env\x18\x05 \x03(\tR\x03env\"\xe5\x02\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\aR\aaddress\x12#\n" +
	"\rprefix_length\x18\x03 \x01(\aR\fprefixLength\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x128\n" +
	"\tcreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tstartedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12#\n" +
	"\rsubnetwork_id\x18\b \x01(\rR\fsubnetworkId\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\t \x03(\tR\n" +
	"entrypoint\x12\x10\n" +
	"\x03cmd\x18\n" +
	" \x03(\tR\x03cmd\x12\x10\n" +
	"\x03env\x18\v \x03(\tR\x03env\"\x8f\x01\n" +
	"\x14ContainerExecRequest\x12V\n" +
	"\x0einitialization\x18\x01 \x01(\v2,.bx2cloud.ContainerExecInitializationRequestH\x00R\x0einitialization\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdinB\a\n" +
	"\x05input\"\x84\x02\n" +
	"\"ContainerExecInitializationRequest\x12P\n" +
	"\x0eidentification\x18\x01 \x01(\v2(.bx2cloud.ContainerIdentificationRequestR\x0eidentification\x12#\n" +
	"\rconsole_width\x18\x02 \x01(\x05R\fconsoleWidth\x12%\n" +
	"\x0econsole_height\x18\x03 \x01(\x05R\rconsoleHeight\x12\x1f\n" +
	"\bterminal\x18\x04 \x01(\tH\x00R\bterminal\x88\x01\x01\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04argsB\v\n" +
	"\t_terminal\"Z\n" +
	"\x15ContainerExecResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x1d\n" +
	"\texit_code\x18\x02 \x01(\x05H\x00R\bexitCodeB\b\n" +
	"\x06output\"\x80\x01\n" +
	"\x14ContainerLogsRequest\x12P\n" +
	"\x0eidentification\x18\x01 \x01(\v2(.bx2cloud.ContainerIdentificationRequestR\x0eidentification\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"1\n" +
	"\x15ContainerLogsResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent2\xc5\x04\n" +
	"\x10ContainerService\x12D\n" +
	"\x03Get\x12(.bx2cloud.ContainerIdentificationRequest\x1a\x13.bx2cloud.Container\x125\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x13.bx2cloud.Container0\x01\x12A\n" +
	"\x06Create\x12\".bx2cloud.ContainerCreationRequest\x1a\x13.bx2cloud.Container\x12J\n" +
	"\x06Delete\x12(.bx2cloud.ContainerIdentificationRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x04Exec\x12\x1e.bx2cloud.ContainerExecRequest\x1a\x1f.bx2cloud.ContainerExecResponse(\x010\x01\x12F\n" +
	"\x05Start\x12(.bx2cloud.ContainerIdentificationRequest\x1a\x13.bx2cloud.Container\x12E\n" +
	"\x04Stop\x12(.bx2cloud.ContainerIdentificationRequest\x1a\x13.bx2cloud.Container\x12I\n" +
	"\x04Logs\x12\x1e.bx2cloud.ContainerLogsRequest\x1a\x1f.bx2cloud.ContainerLogsResponse0\x01B,Z*github.com/BenasB/bx2cloud/internal/api/pbb\x06proto3"

var (
	file_container_proto_rawDescOnce sync.Once
	file_container_proto_rawDescData []byte
)

func file_container_proto_rawDescGZIP() []byte {
	file_container_proto_rawDescOnce.Do(func() {
		file_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_container_proto_rawDesc), len(file_container_proto_rawDesc)))
	})
	return file_container_proto_rawDescData
}

var file_container_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_container_proto_goTypes = []any{
	(*ContainerIdentificationRequest)(nil),     // 0: bx2cloud.ContainerIdentificationRequest
	(*ContainerCreationRequest)(nil),           // 1: bx2cloud.ContainerCreationRequest
	(*Container)(nil),                          // 2: bx2cloud.Container
	(*ContainerExecRequest)(nil),               // 3: bx2cloud.ContainerExecRequest
	(*ContainerExecInitializationRequest)(nil), // 4: bx2cloud.ContainerExecInitializationRequest
	(*ContainerExecResponse)(nil),              // 5: bx2cloud.ContainerExecResponse
	(*ContainerLogsRequest)(nil),               // 6: bx2cloud.ContainerLogsRequest
	(*ContainerLogsResponse)(nil),              // 7: bx2cloud.ContainerLogsResponse
	(*timestamppb.Timestamp)(nil),              // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                      // 9: google.protobuf.Empty
}
var file_container_proto_depIdxs = []int32{
	8,  // 0: bx2cloud.Container.createdAt:type_name -> google.protobuf.Timestamp
	8,  // 1: bx2cloud.Container.startedAt:type_name -> google.protobuf.Timestamp
	4,  // 2: bx2cloud.ContainerExecRequest.initialization:type_name -> bx2cloud.ContainerExecInitializationRequest
	0,  // 3: bx2cloud.ContainerExecInitializationRequest.identification:type_name -> bx2cloud.ContainerIdentificationRequest
	0,  // 4: bx2cloud.ContainerLogsRequest.identification:type_name -> bx2cloud.ContainerIdentificationRequest
	0,  // 5: bx2cloud.ContainerService.Get:input_type -> bx2cloud.ContainerIdentificationRequest
	9,  // 6: bx2cloud.ContainerService.List:input_type -> google.protobuf.Empty
	1,  // 7: bx2cloud.ContainerService.Create:input_type -> bx2cloud.ContainerCreationRequest
	0,  // 8: bx2cloud.ContainerService.Delete:input_type -> bx2cloud.ContainerIdentificationRequest
	3,  // 9: bx2cloud.ContainerService.Exec:input_type -> bx2cloud.ContainerExecRequest
	0,  // 10: bx2cloud.ContainerService.Start:input_type -> bx2cloud.ContainerIdentificationRequest
	0,  // 11: bx2cloud.ContainerService.Stop:input_type -> bx2cloud.ContainerIdentificationRequest
	6,  // 12: bx2cloud.ContainerService.Logs:input_type -> bx2cloud.ContainerLogsRequest
	2,  // 13: bx2cloud.ContainerService.Get:output_type -> bx2cloud.Container
	2,  // 14: bx2cloud.ContainerService.List:output_type -> bx2cloud.Container
	2,  // 15: bx2cloud.ContainerService.Create:output_type -> bx2cloud.Container
	9,  // 16: bx2cloud.ContainerService.Delete:output_type -> google.protobuf.Empty
	5,  // 17: bx2cloud.ContainerService.Exec:output_type -> bx2cloud.ContainerExecResponse
	2,  // 18: bx2cloud.ContainerService.Start:output_type -> bx2cloud.Container
	2,  // 19: bx2cloud.ContainerService.Stop:output_type -> bx2cloud.Container
	7,  // 20: bx2cloud.ContainerService.Logs:output_type -> bx2cloud.ContainerLogsResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_container_proto_init() }
func file_container_proto_init() {
	if File_container_proto != nil {
		return
	}
	file_container_proto_msgTypes[3].OneofWrappers = []any{
		(*ContainerExecRequest_Initialization)(nil),
		(*ContainerExecRequest_Stdin)(nil),
	}
	file_container_proto_msgTypes[4].OneofWrappers = []any{}
	file_container_proto_msgTypes[5].OneofWrappers = []any{
		(*ContainerExecResponse_Stdout)(nil),
		(*ContainerExecResponse_ExitCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_container_proto_rawDesc), len(file_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_container_proto_goTypes,
		DependencyIndexes: file_container_proto_depIdxs,
		MessageInfos:      file_container_proto_msgTypes,
	}.Build()
	File_container_proto = out.File
	file_container_proto_goTypes = nil
	file_container_proto_depIdxs = nil
}
