// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: subnetwork.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubnetworkIdentificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetworkIdentificationRequest) Reset() {
	*x = SubnetworkIdentificationRequest{}
	mi := &file_subnetwork_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetworkIdentificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetworkIdentificationRequest) ProtoMessage() {}

func (x *SubnetworkIdentificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subnetwork_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetworkIdentificationRequest.ProtoReflect.Descriptor instead.
func (*SubnetworkIdentificationRequest) Descriptor() ([]byte, []int) {
	return file_subnetwork_proto_rawDescGZIP(), []int{0}
}

func (x *SubnetworkIdentificationRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SubnetworkCreationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     uint32                 `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Address       uint32                 `protobuf:"fixed32,2,opt,name=address,proto3" json:"address,omitempty"`
	PrefixLength  uint32                 `protobuf:"fixed32,3,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetworkCreationRequest) Reset() {
	*x = SubnetworkCreationRequest{}
	mi := &file_subnetwork_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetworkCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetworkCreationRequest) ProtoMessage() {}

func (x *SubnetworkCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subnetwork_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetworkCreationRequest.ProtoReflect.Descriptor instead.
func (*SubnetworkCreationRequest) Descriptor() ([]byte, []int) {
	return file_subnetwork_proto_rawDescGZIP(), []int{1}
}

func (x *SubnetworkCreationRequest) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *SubnetworkCreationRequest) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *SubnetworkCreationRequest) GetPrefixLength() uint32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

type SubnetworkUpdateRequest struct {
	state          protoimpl.MessageState           `protogen:"open.v1"`
	Identification *SubnetworkIdentificationRequest `protobuf:"bytes,1,opt,name=identification,proto3" json:"identification,omitempty"`
	// TODO: different message for update body, disallow passing different networkId
	Update        *SubnetworkCreationRequest `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetworkUpdateRequest) Reset() {
	*x = SubnetworkUpdateRequest{}
	mi := &file_subnetwork_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetworkUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetworkUpdateRequest) ProtoMessage() {}

func (x *SubnetworkUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subnetwork_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetworkUpdateRequest.ProtoReflect.Descriptor instead.
func (*SubnetworkUpdateRequest) Descriptor() ([]byte, []int) {
	return file_subnetwork_proto_rawDescGZIP(), []int{2}
}

func (x *SubnetworkUpdateRequest) GetIdentification() *SubnetworkIdentificationRequest {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *SubnetworkUpdateRequest) GetUpdate() *SubnetworkCreationRequest {
	if x != nil {
		return x.Update
	}
	return nil
}

type Subnetwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NetworkId     uint32                 `protobuf:"varint,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Address       uint32                 `protobuf:"fixed32,3,opt,name=address,proto3" json:"address,omitempty"`
	PrefixLength  uint32                 `protobuf:"fixed32,4,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subnetwork) Reset() {
	*x = Subnetwork{}
	mi := &file_subnetwork_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subnetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subnetwork) ProtoMessage() {}

func (x *Subnetwork) ProtoReflect() protoreflect.Message {
	mi := &file_subnetwork_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subnetwork.ProtoReflect.Descriptor instead.
func (*Subnetwork) Descriptor() ([]byte, []int) {
	return file_subnetwork_proto_rawDescGZIP(), []int{3}
}

func (x *Subnetwork) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Subnetwork) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *Subnetwork) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *Subnetwork) GetPrefixLength() uint32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

func (x *Subnetwork) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_subnetwork_proto protoreflect.FileDescriptor

const file_subnetwork_proto_rawDesc = "" +
	"\n" +
	"\x10subnetwork.proto\x12\bbx2cloud\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n" +
	"\x1fSubnetworkIdentificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"y\n" +
	"\x19SubnetworkCreationRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\rR\tnetworkId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\aR\aaddress\x12#\n" +
	"\rprefix_length\x18\x03 \x01(\aR\fprefixLength\"\xa9\x01\n" +
	"\x17SubnetworkUpdateRequest\x12Q\n" +
	"\x0eidentification\x18\x01 \x01(\v2).bx2cloud.SubnetworkIdentificationRequestR\x0eidentification\x12;\n" +
	"\x06update\x18\x02 \x01(\v2#.bx2cloud.SubnetworkCreationRequestR\x06update\"\xb4\x01\n" +
	"\n" +
	"Subnetwork\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\rR\tnetworkId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\aR\aaddress\x12#\n" +
	"\rprefix_length\x18\x04 \x01(\aR\fprefixLength\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xe8\x02\n" +
	"\x11SubnetworkService\x12F\n" +
	"\x03Get\x12).bx2cloud.SubnetworkIdentificationRequest\x1a\x14.bx2cloud.Subnetwork\x126\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x14.bx2cloud.Subnetwork0\x01\x12C\n" +
	"\x06Create\x12#.bx2cloud.SubnetworkCreationRequest\x1a\x14.bx2cloud.Subnetwork\x12A\n" +
	"\x06Update\x12!.bx2cloud.SubnetworkUpdateRequest\x1a\x14.bx2cloud.Subnetwork\x12K\n" +
	"\x06Delete\x12).bx2cloud.SubnetworkIdentificationRequest\x1a\x16.google.protobuf.EmptyB,Z*github.com/BenasB/bx2cloud/internal/api/pbb\x06proto3"

var (
	file_subnetwork_proto_rawDescOnce sync.Once
	file_subnetwork_proto_rawDescData []byte
)

func file_subnetwork_proto_rawDescGZIP() []byte {
	file_subnetwork_proto_rawDescOnce.Do(func() {
		file_subnetwork_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subnetwork_proto_rawDesc), len(file_subnetwork_proto_rawDesc)))
	})
	return file_subnetwork_proto_rawDescData
}

var file_subnetwork_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_subnetwork_proto_goTypes = []any{
	(*SubnetworkIdentificationRequest)(nil), // 0: bx2cloud.SubnetworkIdentificationRequest
	(*SubnetworkCreationRequest)(nil),       // 1: bx2cloud.SubnetworkCreationRequest
	(*SubnetworkUpdateRequest)(nil),         // 2: bx2cloud.SubnetworkUpdateRequest
	(*Subnetwork)(nil),                      // 3: bx2cloud.Subnetwork
	(*timestamppb.Timestamp)(nil),           // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 5: google.protobuf.Empty
}
var file_subnetwork_proto_depIdxs = []int32{
	0, // 0: bx2cloud.SubnetworkUpdateRequest.identification:type_name -> bx2cloud.SubnetworkIdentificationRequest
	1, // 1: bx2cloud.SubnetworkUpdateRequest.update:type_name -> bx2cloud.SubnetworkCreationRequest
	4, // 2: bx2cloud.Subnetwork.createdAt:type_name -> google.protobuf.Timestamp
	0, // 3: bx2cloud.SubnetworkService.Get:input_type -> bx2cloud.SubnetworkIdentificationRequest
	5, // 4: bx2cloud.SubnetworkService.List:input_type -> google.protobuf.Empty
	1, // 5: bx2cloud.SubnetworkService.Create:input_type -> bx2cloud.SubnetworkCreationRequest
	2, // 6: bx2cloud.SubnetworkService.Update:input_type -> bx2cloud.SubnetworkUpdateRequest
	0, // 7: bx2cloud.SubnetworkService.Delete:input_type -> bx2cloud.SubnetworkIdentificationRequest
	3, // 8: bx2cloud.SubnetworkService.Get:output_type -> bx2cloud.Subnetwork
	3, // 9: bx2cloud.SubnetworkService.List:output_type -> bx2cloud.Subnetwork
	3, // 10: bx2cloud.SubnetworkService.Create:output_type -> bx2cloud.Subnetwork
	3, // 11: bx2cloud.SubnetworkService.Update:output_type -> bx2cloud.Subnetwork
	5, // 12: bx2cloud.SubnetworkService.Delete:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_subnetwork_proto_init() }
func file_subnetwork_proto_init() {
	if File_subnetwork_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subnetwork_proto_rawDesc), len(file_subnetwork_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subnetwork_proto_goTypes,
		DependencyIndexes: file_subnetwork_proto_depIdxs,
		MessageInfos:      file_subnetwork_proto_msgTypes,
	}.Build()
	File_subnetwork_proto = out.File
	file_subnetwork_proto_goTypes = nil
	file_subnetwork_proto_depIdxs = nil
}
